### ISSUE TITLE
bleemeo agent not working on centos7 system

### ISSUE THREAD

**Issue by RalfK** [bleemeo/bleemeo-agent#5] opened 2019-09-28 14:38 UTC
i installed bleemeo-agent from packages on a centos 7 system. But it is not running. Here some messages in syslog:

```
Sep 28 14:59:02 cree bleemeo-agent[6626]: INFO - Agent starting... (version=19.09.18.125857-1.el7)
Sep 28 14:59:02 cree bleemeo-agent[6626]: INFO - Agent stopped
Sep 28 14:59:02 cree bleemeo-agent: Traceback (most recent call last):
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/bin/bleemeo-agent", line 11, in <module>
Sep 28 14:59:02 cree bleemeo-agent: load_entry_point('bleemeo-agent==0.1', 'console_scripts', 'bleemeo-agent')()
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/lib/python3.6/site-packages/bleemeo_agent/core.py", line 418, in main
Sep 28 14:59:02 cree bleemeo-agent: core.run()
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/lib/python3.6/site-packages/bleemeo_agent/core.py", line 1495, in run
Sep 28 14:59:02 cree bleemeo-agent: self.schedule_tasks()
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/lib/python3.6/site-packages/bleemeo_agent/core.py", line 1754, in schedule_tasks
Sep 28 14:59:02 cree bleemeo-agent: self.update_facts()
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/lib/python3.6/site-packages/bleemeo_agent/core.py", line 2669, in update_facts
Sep 28 14:59:02 cree bleemeo-agent: self.last_facts = bleemeo_agent.facts.get_facts(self)
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/lib/python3.6/site-packages/bleemeo_agent/facts.py", line 646, in get_facts
Sep 28 14:59:02 cree bleemeo-agent: 'public_ip': get_public_ip(core),
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/lib/python3.6/site-packages/bleemeo_agent/facts.py", line 424, in get_public_ip
Sep 28 14:59:02 cree bleemeo-agent: return get_url_content(core, url)
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/lib/python3.6/site-packages/bleemeo_agent/facts.py", line 66, in get_url_content
Sep 28 14:59:02 cree bleemeo-agent: headers={'User-Agent': core.http_user_agent},
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/lib/python3.6/site-packages/requests/api.py", line 75, in get
Sep 28 14:59:02 cree bleemeo-agent: return request('get', url, params=params, **kwargs)
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
Sep 28 14:59:02 cree bleemeo-agent: return session.request(method=method, url=url, **kwargs)
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
Sep 28 14:59:02 cree bleemeo-agent: resp = self.send(prep, **send_kwargs)
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
Sep 28 14:59:02 cree bleemeo-agent: r = adapter.send(request, **kwargs)
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 416, in send
Sep 28 14:59:02 cree bleemeo-agent: self.cert_verify(conn, request.url, verify, cert)
Sep 28 14:59:02 cree bleemeo-agent: File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 228, in cert_verify
Sep 28 14:59:02 cree bleemeo-agent: "invalid path: {}".format(cert_loc))
Sep 28 14:59:02 cree bleemeo-agent: OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /usr/lib/python3.6/site-packages/certifi/cacert.pem
Sep 28 14:59:02 cree systemd: bleemeo-agent.service: main process exited, code=exited, status=1/FAILURE
Sep 28 14:59:02 cree systemd: Unit bleemeo-agent.service entered failed state.
Sep 28 14:59:02 cree systemd: bleemeo-agent.service failed.
Sep 28 14:59:03 cree systemd: bleemeo-agent.service holdoff time over, scheduling restart.
```

**Comment by PierreF** [comment] 2019-09-28 15:13
Hi,

thanks for your report.
I'm not able to reproduce your issue which seems to come from python36-requests and/or python36-certifi package.
Could you tell me the version and where those packages come from ? You should be able to get this information with:
```
$ yum info bleemeo-agent python36-requests python36-certifi
```

I'm especially interested in the "version", "Release" and "From repo" line. For your information on my CentOS, I've:
```
Installed Packages
Name        : bleemeo-agent
Version     : 19.09.18.125857
Release     : 1.el7
From repo   : bleemeo-agent-repo

Name        : python36-certifi
Version     : 2018.10.15
Release     : 5.el7
From repo   : epel

Name        : python36-requests
Version     : 2.12.5
Release     : 3.el7
From repo   : epel
```

**Comment by PierreF** [comment] 2020-04-21 12:36
Closing as I can't reproduce. If you still had this issue, feel free to reopen.

**Closed by PierreF** 2020-04-21 12:36 UTC
